blueprint:
  name: Entity Controller
  description: Turn on/off entity based on sensor
  domain: automation

  input:
    control_entity:
      name: Control Entity
    sensor_entity:
      name: Sensor Entity

mode: restart
max_exceeded: silent

trigger:
  - platform: state
    entity_id: !input sensor_entity
    to: ['on', 'off']
  - platform: homeassistant
    event: start

action:
  - choose:
      - conditions:
          - condition: state
            entity_id: !input sensor_entity
            state: 'off'
        sequence:
          - service: homeassistant.turn_off
            entity_id: !input control_entity
    default:
      - service: homeassistant.turn_on
        entity_id: !input control_entity
