blueprint:
  name: Entity Controller
  description: Turn on/off entity based on sensor
  domain: automation

  input:
    sensor_entity:
      name: Sensor Entity
      selector:
        entity: {}

    control_entity:
      name: Control Entity
      selector:
        target: {}

mode: restart
max_exceeded: silent

variables:
  sensor_entity: !input sensor_entity
  control_entity: !input control_entity

trigger:
  - platform: state
    entity_id: !input sensor_entity
    to: ['on', 'off']
  - platform: homeassistant
    event: start

action:
  - choose:
      - conditions:
          - condition: state
            entity_id: !input sensor_entity
            state: 'off'
        sequence:
          - repeat:
              sequence:
                - variables:
                    entities: >
                      {{
                        expand(control_entity) |
                        selectattr('state', 'eq', 'on') |
                        map(attribute='entity_id') |
                        list
                      }}
                - condition: template
                  value_template: "{{ entities | count > 0 }}"
                - service: homeassistant.turn_off
                  target:
                    entity_id: "{{ entities }}"
                - delay: 10
              until:
                - condition: template
                  value_template: >
                    {{
                      expand(control_entity) |
                      selectattr('state', 'eq', 'on') |
                      map(attribute='entity_id') |
                      list | count == 0
                    }}
    default:
      - repeat:
          sequence:
            - variables:
                entities: >
                  {{
                    expand(control_entity) |
                    selectattr('state', 'eq', 'off') |
                    map(attribute='entity_id') |
                    list
                  }}
            - condition: template
              value_template: "{{ entities | count > 0 }}"
            - service: homeassistant.turn_on
              target:
                entity_id: "{{ entities }}"
            - delay: 10
          until:
            - condition: template
              value_template: >
                {{
                  expand(control_entity) |
                  selectattr('state', 'eq', 'off') |
                  map(attribute='entity_id') |
                  list | count == 0
                }}
