light:
  - platform: group
    unique_id: bathroom
    name: Bathroom Light
    entities:
      - light.bathroom_ceiling
      - light.bathroom_mirror

  - platform: switch
    name: Bathroom Ceiling Light
    entity_id: switch.bathroom_ceiling_light

  - platform: switch
    name: Bathroom Mirror Light
    entity_id: switch.bathroom_mirror_light

automation:
  - alias: Bathroom Light Controller
    id: bathroom_light_controller
    use_blueprint:
      path: entity_controller.yaml
      input:
        sensor_entity: group.bathroom_presence
        control_entity: light.bathroom
