light:
  - platform: group
    unique_id: casino
    name: Casino Light
    entities:
      - light.casino_ceiling

adaptive_lighting:
  - name: Casino
    lights:
      - light.casino_ceiling
    min_brightness: 75

sensor:
  - platform: powercalc
    name: Casino Ceiling Light
    entity_id: light.casino_ceiling
    linear:
      min_power: 0.5
      max_power: 46.5

automation:
  - alias: Casino Light Controller
    id: casino_light_controller
    use_blueprint:
      path: entity_controller.yaml
      input:
        sensor_entity: group.casino_presence
        control_entity: light.casino
