light:
  - platform: group
    unique_id: closet
    name: Closet Light
    entities:
      - light.closet_ceiling

sensor:
  - platform: powercalc
    name: Closet Ceiling Light
    entity_id: light.closet_ceiling

automation:
  - alias: Closet Light Controller
    id: closet_light_controller
    use_blueprint:
      path: entity_controller.yaml
      input:
        sensor_entity: group.closet_presence
        control_entity: light.closet
