group:
  closet_lights:
    name: Closet Lights
    entities:
      - light.closet

sensor:
  - platform: powercalc
    name: Closet Light
    entity_id: light.closet

automation:
  - alias: Closet Light Controller
    id: closet_light_controller
    use_blueprint:
      path: entity_controller.yaml
      input:
        sensor_entity: group.closet_presence
        control_entity: group.closet_lights
