group:
  guest_lights:
    name: Guest Lights
    entities:
      - switch.guest_light

automation:
  - alias: Guest Light Controller
    id: guest_light_controller
    use_blueprint:
      path: entity_controller.yaml
      input:
        sensor_entity: group.guest_presence
        control_entity: group.guest_lights
