light:
  - platform: group
    unique_id: guest
    name: Guest Light
    entities:
      - light.guest_ceiling

  - platform: switch
    name: Guest Ceiling Light
    entity_id: switch.guest_ceiling_light

automation:
  - alias: Guest Light Controller
    id: guest_light_controller
    use_blueprint:
      path: entity_controller.yaml
      input:
        sensor_entity: group.guest_presence
        control_entity: light.guest
