light:
  - platform: group
    unique_id: kids
    name: Kids Light
    entities:
      - light.kids_ceiling

adaptive_lighting:
  - name: Kids
    lights: light.kids
    min_brightness: 50

sensor:
  - platform: powercalc
    name: Kids Ceiling Light
    entity_id: light.kids_ceiling

automation:
  - alias: Kids Light Controller
    id: kids_light_controller
    use_blueprint:
      path: entity_controller.yaml
      input:
        sensor_entity: group.kids_presence
        control_entity: light.kids
