light:
  - platform: group
    unique_id: kitchen
    name: Kitchen Light
    entities:
      - light.kitchen_back
      - light.kitchen_front
      - light.kitchen_fume

  - platform: switch
    name: Kitchen Back Light
    entity_id: switch.kitchen_back_light

  - platform: switch
    name: Kitchen Front Light
    entity_id: switch.kitchen_front_light

  - platform: switch
    name: Kitchen Fume Light
    entity_id: switch.kitchen_fume_light

automation:
  - alias: Kitchen Light Controller
    id: kitchen_light_controller
    use_blueprint:
      path: entity_controller.yaml
      input:
        sensor_entity: group.kitchen_presence
        control_entity: light.kitchen
