light:
  - platform: group
    unique_id: lounge
    name: Lounge Light
    entities:
      - light.lounge_back
      - light.lounge_ceiling
      - light.lounge_glitter
      - light.lounge_tv

  - platform: switch
    name: Lounge Glitter Light
    entity_id: switch.lounge_glitter_light

adaptive_lighting:
  - name: Lounge Ambient
    lights:
      - light.lounge_back
      - light.lounge_tv
    min_brightness: 75

  - name: Lounge Ceiling
    lights:
      - light.lounge_ceiling

sensor:
  - platform: powercalc
    name: Lounge Back Light
    entity_id: light.lounge_back
    linear:
      calibrate:
        - 1 -> 0.3
        - 100 -> 0.8
        - 150 -> 2.1
        - 150 -> 2.1
        - 200 -> 7.1
        - 210 -> 9.3
        - 220 -> 12.1
        - 230 -> 15.8
        - 240 -> 20.7
        - 250 -> 27.2
        - 255 -> 30.3

  - platform: powercalc
    name: Lounge Ceiling Light
    entity_id: light.lounge_ceiling
    linear:
      min_power: 0.5
      max_power: 24.5

  - platform: powercalc
    name: Lounge TV Light
    entity_id: light.lounge_tv
    linear:
      calibrate:
        - 1 -> 0.3
        - 200 -> 3.8
        - 210 -> 5.0
        - 220 -> 6.3
        - 230 -> 8.2
        - 240 -> 10.7
        - 250 -> 13.9
        - 255 -> 15.5

automation:
  - alias: Lounge Back Light Controller
    id: lounge_back_light_controller
    use_blueprint:
      path: entity_controller.yaml
      input:
        sensor_entity: group.lounge_presence
        control_entity: light.lounge_back

  - alias: Lounge Ceiling Light Controller
    id: lounge_ceiling_light_controller
    use_blueprint:
      path: entity_controller.yaml
      input:
        sensor_entity: group.lounge_presence
        control_entity: light.lounge_ceiling

  - alias: Lounge Glitter Light Controller
    id: lounge_glitter_light_controller
    use_blueprint:
      path: entity_controller.yaml
      input:
        sensor_entity: group.lounge_presence
        control_entity: light.lounge_glitter

  - alias: Lounge TV Light Controller
    id: lounge_tv_light_controller
    use_blueprint:
      path: entity_controller.yaml
      input:
        sensor_entity: group.lounge_presence
        control_entity: light.lounge_tv

  - alias: Lounge Light On
    id: lounge_light_on
    mode: restart
    trigger:
      - platform: event
        event_type: zha_event
        event_data:
          device_ieee: '00:17:88:01:04:ae:f3:37'
          endpoint_id: 2
          command: on_short_release
    action:
      - service: automation.turn_on
        target:
          entity_id:
            - automation.lounge_back_light_controller
            - automation.lounge_ceiling_light_controller
            - automation.lounge_glitter_light_controller
            - automation.lounge_tv_light_controller
      - service: automation.trigger
        target:
          entity_id:
            - automation.lounge_back_light_controller
            - automation.lounge_ceiling_light_controller
            - automation.lounge_glitter_light_controller
            - automation.lounge_tv_light_controller

  - alias: Lounge Light Up
    id: lounge_light_up
    mode: restart
    trigger:
      - platform: event
        event_type: zha_event
        event_data:
          device_ieee: '00:17:88:01:04:ae:f3:37'
          endpoint_id: 2
          command: up_short_release
    action:
      - choose:
          - conditions: >
              {{ is_state('automation.lounge_tv_light_controller', 'off') }}
            sequence:
              - service: automation.turn_on
                entity_id: automation.lounge_tv_light_controller
              - service: automation.trigger
                entity_id: automation.lounge_tv_light_controller
          - conditions: >
              {{ is_state('automation.lounge_back_light_controller', 'off') }}
            sequence:
              - service: automation.turn_on
                entity_id: automation.lounge_back_light_controller
              - service: automation.trigger
                entity_id: automation.lounge_back_light_controller
          - conditions: >
              {{ is_state('automation.lounge_glitter_light_controller', 'off') }}
            sequence:
              - service: automation.turn_on
                entity_id: automation.lounge_glitter_light_controller
              - service: automation.trigger
                entity_id: automation.lounge_glitter_light_controller
          - conditions: >
              {{ is_state('automation.lounge_ceiling_light_controller', 'off') }}
            sequence:
              - service: automation.turn_on
                entity_id: automation.lounge_ceiling_light_controller
              - service: automation.trigger
                entity_id: automation.lounge_ceiling_light_controller

  - alias: Lounge Light Down
    id: lounge_light_down
    mode: restart
    trigger:
      - platform: event
        event_type: zha_event
        event_data:
          device_ieee: '00:17:88:01:04:ae:f3:37'
          endpoint_id: 2
          command: down_short_release
    action:
      - choose:
          - conditions: >
              {{ is_state('automation.lounge_ceiling_light_controller', 'on') }}
            sequence:
              - service: automation.turn_off
                entity_id: automation.lounge_ceiling_light_controller
              - service: light.turn_off
                entity_id: light.lounge_ceiling
          - conditions: >
              {{ is_state('automation.lounge_glitter_light_controller', 'on') }}
            sequence:
              - service: automation.turn_off
                entity_id: automation.lounge_glitter_light_controller
              - service: light.turn_off
                entity_id: light.lounge_glitter
          - conditions: >
              {{ is_state('automation.lounge_back_light_controller', 'on') }}
            sequence:
              - service: automation.turn_off
                entity_id: automation.lounge_back_light_controller
              - service: light.turn_off
                entity_id: light.lounge_back
          - conditions: >
              {{ is_state('automation.lounge_tv_light_controller', 'on') }}
            sequence:
              - service: automation.turn_off
                entity_id: automation.lounge_tv_light_controller
              - service: light.turn_off
                entity_id: light.lounge_tv

  - alias: Lounge Light Off
    id: lounge_light_off
    mode: restart
    trigger:
      - platform: event
        event_type: zha_event
        event_data:
          device_ieee: '00:17:88:01:04:ae:f3:37'
          endpoint_id: 2
          command: off_short_release
    action:
      - service: automation.turn_off
        target:
          entity_id:
            - automation.lounge_back_light_controller
            - automation.lounge_ceiling_light_controller
            - automation.lounge_glitter_light_controller
            - automation.lounge_tv_light_controller
      - service: light.turn_off
        entity_id: light.lounge
