template:
  - binary_sensor:
      - name: Max Sonos
        unique_id: max_sonos
        state: "{{ is_state('media_player.max_sonos', 'playing') }}"

sensor:
  - platform: powercalc
    entity_id: media_player.max_sonos
    fixed:
      states_power:
        playing: 4.2
        paused: 3.5
        idle: 3.5
