light:
  - platform: group
    unique_id: office
    name: Office Light
    entities:
      - light.office_back
      - light.office_front
      - light.office_middle

  - platform: switch
    name: Office Back Light
    entity_id: switch.office_back_light

  - platform: switch
    name: Office Front Light
    entity_id: switch.office_front_light

sensor:
  - platform: powercalc
    name: Office Middle Light
    entity_id: light.office_middle

automation:
  - alias: Office Light Controller
    id: office_light_controller
    use_blueprint:
      path: entity_controller.yaml
      input:
        sensor_entity: group.office_presence
        control_entity: light.office
