light:
  - platform: group
    unique_id: wc
    name: WC Light
    entities:
      - light.wc_ceiling

  - platform: switch
    name: WC Ceiling Light
    entity_id: switch.wc_ceiling_light

automation:
  - alias: WC Light Controller
    id: wc_light_controller
    use_blueprint:
      path: entity_controller.yaml
      input:
        sensor_entity: group.wc_presence
        control_entity: light.wc
